<?php

namespace ContainerJfLjaYs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EXlc43oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EXlc43o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EXlc43o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'aboutUs' => ['privates', '.errored..service_locator.EXlc43o.App\\Entity\\AboutUs', NULL, 'Cannot autowire service ".service_locator.EXlc43o": it needs an instance of "App\\Entity\\AboutUs" but this type has been excluded in "config/services.yaml".'],
        ], [
            'aboutUs' => 'App\\Entity\\AboutUs',
        ]);
    }
}
