<?php

<<<<<<<< HEAD:var/cache/dev/ContainerXT7JE5o/get_ServiceLocator_Fj21OfDService.php
namespace ContainerXT7JE5o;
========
namespace ContainerZ7VZQp1;
>>>>>>>> d4de6d14 (Correction AboutUs):var/cache/dev/ContainerZ7VZQp1/get_ServiceLocator_Fj21OfDService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fj21OfDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fj21OfD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fj21OfD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'newz' => ['privates', '.errored..service_locator.fj21OfD.App\\Entity\\Newz', NULL, 'Cannot autowire service ".service_locator.fj21OfD": it needs an instance of "App\\Entity\\Newz" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'newz' => 'App\\Entity\\Newz',
        ]);
    }
}
