<?php

<<<<<<<< HEAD:var/cache/dev/ContainerXT7JE5o/getAssetMapper_Importmap_Command_RemoveService.php
namespace ContainerXT7JE5o;
========
namespace ContainerZ7VZQp1;
>>>>>>>> d4de6d14 (Correction AboutUs):var/cache/dev/ContainerZ7VZQp1/getAssetMapper_Importmap_Command_RemoveService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetMapper_Importmap_Command_RemoveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'asset_mapper.importmap.command.remove' shared service.
     *
     * @return \Symfony\Component\AssetMapper\Command\ImportMapRemoveCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/asset-mapper/Command/ImportMapRemoveCommand.php';

        $container->privates['asset_mapper.importmap.command.remove'] = $instance = new \Symfony\Component\AssetMapper\Command\ImportMapRemoveCommand(($container->privates['asset_mapper.importmap.manager'] ?? $container->load('getAssetMapper_Importmap_ManagerService')));

        $instance->setName('importmap:remove');
        $instance->setDescription('Remove JavaScript packages');

        return $instance;
    }
}
