<?php

<<<<<<<< HEAD:var/cache/dev/ContainerXT7JE5o/getAboutUsControllerService.php
namespace ContainerXT7JE5o;
========
namespace ContainerZ7VZQp1;
>>>>>>>> d4de6d14 (Correction AboutUs):var/cache/dev/ContainerZ7VZQp1/getAboutUsControllerService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAboutUsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AboutUsController' shared autowired service.
     *
     * @return \App\Controller\AboutUsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AboutUsController.php';

        $container->services['App\\Controller\\AboutUsController'] = $instance = new \App\Controller\AboutUsController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\AboutUsController', $container));

        return $instance;
    }
}
