<?php

<<<<<<<< HEAD:var/cache/dev/ContainerXT7JE5o/getAboutTypeService.php
namespace ContainerXT7JE5o;
========
namespace ContainerZ7VZQp1;
>>>>>>>> d4de6d14 (Correction AboutUs):var/cache/dev/ContainerZ7VZQp1/getAboutTypeService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAboutTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AboutType' shared autowired service.
     *
     * @return \App\Form\AboutType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AboutType.php';

        return $container->privates['App\\Form\\AboutType'] = new \App\Form\AboutType();
    }
}
