<?php

<<<<<<<< HEAD:var/cache/dev/ContainerXT7JE5o/getBatchActionDtoService.php
namespace ContainerXT7JE5o;
========
namespace ContainerZ7VZQp1;
>>>>>>>> d4de6d14 (Correction AboutUs):var/cache/dev/ContainerZ7VZQp1/getBatchActionDtoService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBatchActionDtoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.twrFs.m.EasyCorp\Bundle\EasyAdminBundle\Dto\BatchActionDto' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Dto\BatchActionDto
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.twrFs.m": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Dto\\BatchActionDto" but no such service exists.');
    }
}
