<?php

<<<<<<<< HEAD:var/cache/dev/ContainerXT7JE5o/getFieldCollectionService.php
namespace ContainerXT7JE5o;
========
namespace ContainerZ7VZQp1;
>>>>>>>> d4de6d14 (Correction AboutUs):var/cache/dev/ContainerZ7VZQp1/getFieldCollectionService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFieldCollectionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lng3o3t.EasyCorp\Bundle\EasyAdminBundle\Collection\FieldCollection' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Collection\FieldCollection
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lng3o3t": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Collection\\FieldCollection" but no such service exists.');
    }
}
