<?php

<<<<<<<< HEAD:var/cache/dev/ContainerXT7JE5o/getMailerTypeService.php
namespace ContainerXT7JE5o;
========
namespace ContainerZ7VZQp1;
>>>>>>>> d4de6d14 (Correction AboutUs):var/cache/dev/ContainerZ7VZQp1/getMailerTypeService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailerTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\MailerType' shared autowired service.
     *
     * @return \App\Form\MailerType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/MailerType.php';

        return $container->privates['App\\Form\\MailerType'] = new \App\Form\MailerType();
    }
}
