<?php

<<<<<<<< HEAD:var/cache/dev/ContainerXT7JE5o/getNewzService.php
namespace ContainerXT7JE5o;
========
namespace ContainerZ7VZQp1;
>>>>>>>> d4de6d14 (Correction AboutUs):var/cache/dev/ContainerZ7VZQp1/getNewzService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Do0b7WP.App\Entity\Newz' shared service.
     *
     * @return \App\Entity\Newz
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Do0b7WP": it needs an instance of "App\\Entity\\Newz" but this type has been excluded in "config/services.yaml".');
    }
}
