<?php

<<<<<<<< HEAD:var/cache/dev/ContainerXT7JE5o/getUser3Service.php
namespace ContainerXT7JE5o;
========
namespace ContainerZ7VZQp1;
>>>>>>>> d4de6d14 (Correction AboutUs):var/cache/dev/ContainerZ7VZQp1/getUser3Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUser3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.R0Sb2kd.App\Entity\User' shared service.
     *
     * @return \App\Entity\User
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.R0Sb2kd": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".');
    }
}
