<?php

namespace Container8K1xAU1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnsubscribeTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\UnsubscribeType' shared autowired service.
     *
     * @return \App\Form\UnsubscribeType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/UnsubscribeType.php';

        return $container->privates['App\\Form\\UnsubscribeType'] = new \App\Form\UnsubscribeType();
    }
}
