<?php

namespace Container5ugmXBW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbonnementRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AbonnementRepository' shared autowired service.
     *
     * @return \App\Repository\AbonnementRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AbonnementRepository'] = new \App\Repository\AbonnementRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
