<?php

namespace Container5ugmXBW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailDataRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\MailDataRepository' shared autowired service.
     *
     * @return \App\Repository\MailDataRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\MailDataRepository'] = new \App\Repository\MailDataRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
