<?php

namespace Container5ugmXBW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrivacyControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\PrivacyController' shared autowired service.
     *
     * @return \App\Controller\PrivacyController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\PrivacyController'] = $instance = new \App\Controller\PrivacyController();

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\PrivacyController', $container));

        return $instance;
    }
}
