<?php

namespace Container5ugmXBW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscriberRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SubscriberRepository' shared autowired service.
     *
     * @return \App\Repository\SubscriberRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SubscriberRepository'] = new \App\Repository\SubscriberRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
