<?php

namespace Container5ugmXBW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscriberTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\SubscriberType' shared autowired service.
     *
     * @return \App\Form\SubscriberType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\SubscriberType'] = new \App\Form\SubscriberType();
    }
}
