<?php

namespace ContainerObus9HP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Nv4Q7JWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Nv4Q7JW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Nv4Q7JW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'aboutUsRepository' => ['privates', 'App\\Repository\\AboutUsRepository', 'getAboutUsRepositoryService', true],
            'actionRepositor' => ['privates', 'App\\Repository\\ActionRepository', 'getActionRepositoryService', true],
            'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'newzRepository' => ['privates', 'App\\Repository\\NewzRepository', 'getNewzRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'aboutUsRepository' => 'App\\Repository\\AboutUsRepository',
            'actionRepositor' => 'App\\Repository\\ActionRepository',
            'articleRepository' => 'App\\Repository\\ArticleRepository',
            'newzRepository' => 'App\\Repository\\NewzRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
