<?php

namespace ContainerObus9HP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAboutUsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AboutUsController' shared autowired service.
     *
     * @return \App\Controller\AboutUsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AboutUsController.php';

        $container->services['App\\Controller\\AboutUsController'] = $instance = new \App\Controller\AboutUsController();

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\AboutUsController', $container));

        return $instance;
    }
}
