<?php

namespace ContainerUo4fz7p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewz3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fj21OfD.App\Entity\Newz' shared service.
     *
     * @return \App\Entity\Newz
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fj21OfD": it needs an instance of "App\\Entity\\Newz" but this type has been excluded in "config/services.yaml".');
    }
}
