<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ7VZQp1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ7VZQp1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ7VZQp1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ7VZQp1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ7VZQp1\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z7VZQp1',
    'container.build_id' => '76c7fc3d',
    'container.build_time' => 1716327199,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ7VZQp1');
