<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXT7JE5o\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXT7JE5o/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXT7JE5o.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXT7JE5o\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXT7JE5o\App_KernelDevDebugContainer([
    'container.build_hash' => 'XT7JE5o',
    'container.build_id' => 'edb098a5',
    'container.build_time' => 1716406599,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXT7JE5o');
