<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Article extends \App\Entity\Article implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'auteur' => [parent::class, 'auteur', null],
        "\0".parent::class."\0".'contenu' => [parent::class, 'contenu', null],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null],
        "\0".parent::class."\0".'image1' => [parent::class, 'image1', null],
        "\0".parent::class."\0".'image2' => [parent::class, 'image2', null],
        "\0".parent::class."\0".'image3' => [parent::class, 'image3', null],
        "\0".parent::class."\0".'paragraphe1' => [parent::class, 'paragraphe1', null],
        "\0".parent::class."\0".'paragraphe2' => [parent::class, 'paragraphe2', null],
        "\0".parent::class."\0".'paragraphe3' => [parent::class, 'paragraphe3', null],
        "\0".parent::class."\0".'paragraphe4' => [parent::class, 'paragraphe4', null],
        "\0".parent::class."\0".'paragraphe5' => [parent::class, 'paragraphe5', null],
        "\0".parent::class."\0".'paragraphe6' => [parent::class, 'paragraphe6', null],
        "\0".parent::class."\0".'paragraphe7' => [parent::class, 'paragraphe7', null],
        "\0".parent::class."\0".'paragraphe8' => [parent::class, 'paragraphe8', null],
        "\0".parent::class."\0".'paragraphe9' => [parent::class, 'paragraphe9', null],
        "\0".parent::class."\0".'paragraphe10' => [parent::class, 'paragraphe10', null],
        "\0".parent::class."\0".'sousTitre1' => [parent::class, 'sousTitre1', null],
        "\0".parent::class."\0".'sousTitre2' => [parent::class, 'sousTitre2', null],
        "\0".parent::class."\0".'sousTitre3' => [parent::class, 'sousTitre3', null],
        "\0".parent::class."\0".'sousTitre4' => [parent::class, 'sousTitre4', null],
        "\0".parent::class."\0".'sousTitre5' => [parent::class, 'sousTitre5', null],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null],
        'auteur' => [parent::class, 'auteur', null],
        'contenu' => [parent::class, 'contenu', null],
        'date' => [parent::class, 'date', null],
        'description' => [parent::class, 'description', null],
        'id' => [parent::class, 'id', null],
        'image' => [parent::class, 'image', null],
        'image1' => [parent::class, 'image1', null],
        'image2' => [parent::class, 'image2', null],
        'image3' => [parent::class, 'image3', null],
        'paragraphe1' => [parent::class, 'paragraphe1', null],
        'paragraphe2' => [parent::class, 'paragraphe2', null],
        'paragraphe3' => [parent::class, 'paragraphe3', null],
        'paragraphe4' => [parent::class, 'paragraphe4', null],
        'paragraphe5' => [parent::class, 'paragraphe5', null],
        'paragraphe6' => [parent::class, 'paragraphe6', null],
        'paragraphe7' => [parent::class, 'paragraphe7', null],
        'paragraphe8' => [parent::class, 'paragraphe8', null],
        'paragraphe9' => [parent::class, 'paragraphe9', null],
        'paragraphe10' => [parent::class, 'paragraphe10', null],
        'sousTitre1' => [parent::class, 'sousTitre1', null],
        'sousTitre2' => [parent::class, 'sousTitre2', null],
        'sousTitre3' => [parent::class, 'sousTitre3', null],
        'sousTitre4' => [parent::class, 'sousTitre4', null],
        'sousTitre5' => [parent::class, 'sousTitre5', null],
        'titre' => [parent::class, 'titre', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
