<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'abonnements' => [parent::class, 'abonnements', null],
        "\0".parent::class."\0".'adhesionPaye' => [parent::class, 'adhesionPaye', null],
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null],
        "\0".parent::class."\0".'civilite' => [parent::class, 'civilite', null],
        "\0".parent::class."\0".'codePostal' => [parent::class, 'codePostal', null],
        "\0".parent::class."\0".'complementAdresse' => [parent::class, 'complementAdresse', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'formeJuridique' => [parent::class, 'formeJuridique', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'pays' => [parent::class, 'pays', null],
        "\0".parent::class."\0".'plainPassword' => [parent::class, 'plainPassword', null],
        "\0".parent::class."\0".'plan' => [parent::class, 'plan', null],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null],
        "\0".parent::class."\0".'resetPasswordToken' => [parent::class, 'resetPasswordToken', null],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null],
        "\0".parent::class."\0".'siren' => [parent::class, 'siren', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        "\0".parent::class."\0".'ville' => [parent::class, 'ville', null],
        'abonnements' => [parent::class, 'abonnements', null],
        'adhesionPaye' => [parent::class, 'adhesionPaye', null],
        'adresse' => [parent::class, 'adresse', null],
        'civilite' => [parent::class, 'civilite', null],
        'codePostal' => [parent::class, 'codePostal', null],
        'complementAdresse' => [parent::class, 'complementAdresse', null],
        'email' => [parent::class, 'email', null],
        'formeJuridique' => [parent::class, 'formeJuridique', null],
        'id' => [parent::class, 'id', null],
        'nom' => [parent::class, 'nom', null],
        'password' => [parent::class, 'password', null],
        'pays' => [parent::class, 'pays', null],
        'plainPassword' => [parent::class, 'plainPassword', null],
        'plan' => [parent::class, 'plan', null],
        'prenom' => [parent::class, 'prenom', null],
        'resetPasswordToken' => [parent::class, 'resetPasswordToken', null],
        'role' => [parent::class, 'role', null],
        'siren' => [parent::class, 'siren', null],
        'status' => [parent::class, 'status', null],
        'telephone' => [parent::class, 'telephone', null],
        'type' => [parent::class, 'type', null],
        'ville' => [parent::class, 'ville', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
