<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Abonnement extends \App\Entity\Abonnement implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'currentPeriodEnd' => [parent::class, 'currentPeriodEnd', null],
        "\0".parent::class."\0".'currentPeriodStart' => [parent::class, 'currentPeriodStart', null],
        "\0".parent::class."\0".'facture' => [parent::class, 'facture', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null],
        "\0".parent::class."\0".'plan' => [parent::class, 'plan', null],
        "\0".parent::class."\0".'stripeId' => [parent::class, 'stripeId', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'currentPeriodEnd' => [parent::class, 'currentPeriodEnd', null],
        'currentPeriodStart' => [parent::class, 'currentPeriodStart', null],
        'facture' => [parent::class, 'facture', null],
        'id' => [parent::class, 'id', null],
        'isActive' => [parent::class, 'isActive', null],
        'plan' => [parent::class, 'plan', null],
        'stripeId' => [parent::class, 'stripeId', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
