<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Facture extends \App\Entity\Facture implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'abonnement' => [parent::class, 'abonnement', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'hostedUrlFacture' => [parent::class, 'hostedUrlFacture', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'montantPaye' => [parent::class, 'montantPaye', null],
        "\0".parent::class."\0".'noFacture' => [parent::class, 'noFacture', null],
        "\0".parent::class."\0".'stripeId' => [parent::class, 'stripeId', null],
        'abonnement' => [parent::class, 'abonnement', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'hostedUrlFacture' => [parent::class, 'hostedUrlFacture', null],
        'id' => [parent::class, 'id', null],
        'montantPaye' => [parent::class, 'montantPaye', null],
        'noFacture' => [parent::class, 'noFacture', null],
        'stripeId' => [parent::class, 'stripeId', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
